version: '3.0'

services:
  mysql:    
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./Database:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql    
    environment:
        - MYSQL_ROOT_PASSWORD=secret
    restart: always

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8888:80"
    links:
      - mysql:mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=secret
      - PMA_HOST=mysql

  api:
     depends_on:
       - mysql
     image: example/api:runtime
     ports:
       - "5001:80"
     build:
       context: .
       dockerfile: PortfolioSiteExample.Api/Dockerfile     

  frontend:
     depends_on:
       - api
     image: example/frontend:runtime
     ports:
       - "80:80"
     build:
       context: .
       dockerfile: PortfolioSiteExample.Frontend/Dockerfile     
      
volumes:
  mysql-data:
    driver: local