SET CHARSET UTF8;
DROP DATABASE IF EXISTS Example;
CREATE DATABASE Example DEFAULT CHARACTER SET utf8;

Use Example;

SET CHARACTER_SET_CLIENT = utf8;
SET CHARACTER_SET_CONNECTION = utf8;

DROP TABLE IF EXISTS `Examples`;

CREATE TABLE `Examples` (
   `ExampleId` INT AUTO_INCREMENT PRIMARY KEY,
   `Test` VARCHAR(100) NULL
);
